version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env

  backend:
    build: .
    container_name: spiderverse_api
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    env_file:
      - .env
    restart: always

volumes:
  mysql_data: